# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('bar_card', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('full_name', models.CharField(max_length=120)),
                ('status', models.CharField(blank=True, max_length=120, null=True)),
                ('company', models.CharField(blank=True, max_length=120, null=True)),
                ('practice_areas', models.CharField(blank=True, max_length=480, null=True)),
                ('address', models.CharField(max_length=120)),
                ('practice_location', models.CharField(blank=True, max_length=120, null=True)),
                ('gmaps_img', models.CharField(blank=True, max_length=2000, null=True)),
                ('profile_img', models.CharField(blank=True, max_length=2000, null=True)),
                ('license_date', models.CharField(blank=True, max_length=60, null=True)),
                ('statutory_profile_date', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
