# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appellate_court', models.CharField(blank=True, max_length=480, null=True)),
                ('coa_case_number', models.CharField(blank=True, max_length=480, null=True)),
                ('case_number', models.CharField(blank=True, max_length=480, null=True)),
                ('case_type', models.CharField(blank=True, max_length=480, null=True)),
                ('date_filed', models.CharField(blank=True, max_length=480, null=True)),
                ('style', models.CharField(blank=True, max_length=480, null=True)),
                ('trial_court', models.CharField(blank=True, max_length=480, null=True)),
                ('trial_court_case_number', models.CharField(blank=True, max_length=480, null=True)),
                ('trial_court_county', models.CharField(blank=True, max_length=480, null=True)),
                ('v', models.CharField(blank=True, max_length=480, null=True)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawyers.Lawyer')),
            ],
        ),
    ]
