# Generated by Django 2.0.2 on 2018-02-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0002_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='appellate_briefs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='calendars',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='case_events',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='parties',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='trial_court_information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
